### ISSUE TITLE
Puppet 7 Support

### ISSUE THREAD

**Issue by QueerCodingGirl** [voxpupuli/puppet-drbd#109]
Are there any plans to test this on puppet 7 and change the metadata.json to support puppet 7?

**Comment by zilchms** [comment]
Puppet 7 support was added with: https://github.com/voxpupuli/puppet-drbd/commit/aaeb91fdba8c73e9b9a6753612b21dbe5b476533
Puppet 8 support was added with: https://github.com/voxpupuli/puppet-drbd/commit/5bc57022e7ad6231315ab042a9b819c5d22edffd
