### ISSUE TITLE
Package name needs to be configurable

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/puppet-drbd#25]
Package name isn't always `drbd8-utils`
http://elrepo.org/tiki/drbd84-utils

**Comment by alexjfisher** [comment]
Fixed in https://github.com/voxpupuli/puppet-drbd/pull/28

**Comment by and0x000** [comment]
This is already configurable (not sure though, if it was at the point when this issue was raised). 

```
class { 'drbd':
  package_name => 'drbd-utils',
}
```
related to #90

**Comment by dhoppe** [comment]
@alexjfisher I think this issue can be closed. What do you think?

**Comment by alexjfisher** [comment]
Fixed in https://github.com/voxpupuli/puppet-drbd/pull/39
