### ISSUE TITLE
Update dependency towards concat module

### ISSUE THREAD

**Issue by Kyoshiro-san** [voxpupuli/puppet-drbd#60]
Hi,

I'm currently using puppet with concat module version v4.1.1 (github master) and I'm getting this notice in puppet master:

> Warning: Module 'puppetlabs-concat' (v4.1.1) fails to meet some dependencies:
  'puppet-drbd' (v0.5.1-rc0) requires 'puppetlabs-concat' (>= 1.2.5 < 3.0.0)

If I use concat version 2.2.1 (latest version < 3.0.0) I get a lot of dependencies errors from other modules. I think you could increase required concat module version to a more recent one. I suppose you have tests to check it's ok, but on my side, no problem with concat v4.1.1.

Cheers !
Kyoshiro

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.8.2-5~bpo8+1
- Ruby: 2.1.5+deb8u2
- Distribution: Debian Jessie (backports)
- Module version: 0.5.1-rc0 (guthub master)

**Comment by ekohl** [comment]
We encourage submitting a PR to change ```metadata.json``` to allow that version. Would you be willing to submit a PR?

**Comment by Kyoshiro-san** [comment]
Hi,

No worries, I'll open a PR, although I must say I haven't checked all features.
I'll open a PR now with my version as latest allowed version, feel free to change it to whatever version you see fit !

Cheers

**Comment by Kyoshiro-san** [comment]
Cheers !
Keep up the good work :-)
